export interface PokemonCsv {
    pokedex_number: string,
    name: string,
    generation: string,
    status: string,
    species: string,
    type_1: string,
    type_2: string,
    height_m: string,
    weight_kg: string,
    ability_1: string,
    ability_2: string,
    ability_hidden: string,
    total_points: string,
    hp: string,
    attack: string,
    defense: string,
    sp_attack: string,
    sp_defense: string,
    speed: string,
}